PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE students(id integer primary key asc,name varchar(30));
INSERT INTO "students" VALUES(1,'Anders Andersson');
INSERT INTO "students" VALUES(2,'Beata Bengtsson');
INSERT INTO "students" VALUES(3,'Charlie Christensen');
INSERT INTO "students" VALUES(4,'Dick Dale');
INSERT INTO "students" VALUES(5,'Edward Eriksson');
CREATE TABLE courses(id integer primary key asc,course_code varchar(12));
INSERT INTO "courses" VALUES(1,'TIG015');
INSERT INTO "courses" VALUES(2,'TIG058');
CREATE TABLE registrations(student_id int(8), course_id int(8));
INSERT INTO "registrations" VALUES(1,1);
INSERT INTO "registrations" VALUES(1,2);
INSERT INTO "registrations" VALUES(2,2);
INSERT INTO "registrations" VALUES(3,1);
INSERT INTO "registrations" VALUES(4,1);
INSERT INTO "registrations" VALUES(4,2);
INSERT INTO "registrations" VALUES(5,2);
COMMIT;
